export default {
  "BASE_URL" : "https://api-soida.applamdep.com",
  //"BASE_URL" : "http://localhost:3002",
  "LIST_USER" : "/api/list-user",
  "LIST_USER_WITH_ID" : "/api/list-user?id=",
  "ADD_USER" : "/api/add-user",
  "UPDATE_USER" : "/api/update-user",
  "DELETE_USER" : "/api/delete-user",
  "LOGIN_ADMIN" : "/api/login_admin",
  "GET_SHOP" : "/api/get-shop",
  "GET_SALE" : "/api/get-sale",
  "GET_COEFFICIENT" : "/api/calculator-coefficient-user",
  "GET_COEFFICIENT_PER_SALE" : "/api/calculator-coefficient-user-per-sale",
  "GET_USER_SALE_BY_MONTH" : "/api/get-user-of-sale-by-month",
  "CALCULATOR_ALL_USER_OF_COMPANY" : "/api/calculator-all-user-company",
  "CALCULATOR_ALL_USER_OF_SALE" : "/api/calculator-all-user-of-sale",
  "GET_SEEDER" : "/api/get-seed",
  "GET_SALE_NAME": "/api/get-name-sale",
  "GET_USER_BY_ID": "/api/get-user-byID",

  "LIST_CUSTOMER" : "/api/list-customer",
  "LIST_CUSTOMER_BY_MONTH" : "/api/get-user-sale-by-month",

  "LIST_TYPEKEY" : "/api/list-typekey",
  "LIST_TYPEKEY_WITH_ID" : "/api/list-typekey?id=",
  "ADD_TYPEKEY" : "/api/add-typekey",
  "UPDATE_TYPEKEY" : "/api/update-typekey",
  "DELETE_TYPEKEY" : "/api/delete-typekey",

  "LIST_HARDWARE" : "/api/list-hardware",
  "LIST_HARDWARE_WITH_ID" : "/api/list-hardware?id=",
  "ADD_HARDWARE" : "/api/add-hardware",
  "UPDATE_HARDWARE" : "/api/update-hardware",
  "DELETE_HARDWARE" : "/api/delete-hardware",

  "LIST_ORDER" : "/api/list-order",
  "LIST_ORDER_BY_SALE" : "/api/plugin-list-order-by-saleid",
  "ADD_ORDER" : "/api/add-order",
  "UPDATE_STATUS_ORDER" : "/api/update-status-order",
  "CHECK_OUT": "/api/checkout-order",

  "LIST_TRANSACTION" : "/api/list-transaction",
  "ADD_TRANSACTION" : "/api/add-transaction",

  "LIST_CHECK_OUT" : "/api/list-checkout",
  "LIST_HARDWARE_CHECKOUT" : "/api/get-list-hardward-by-check-out",
  "UPDATE_STATUS_CHECKOUT" : "/api/update-status-hardware",

  "LIST_ORDER_DETAIL" : "/api/list-orderdetail",
  "ADD_ORDER_DETAIL" : "/api/add-orderdetail",

  "LIST_ROLE" : "/api/list-role",
  "LIST_ROLE_WITH_ID" : "/api/list-role?id=",
  "ADD_ROLE" : "/api/add-role",
  "UPDATE_ROLE" : "/api/update-role",
  "DELETE_ROLE" : "/api/delete-role",

  "LIST_PACKAGE" : "/api/list-package",
  "ADD_PACKAGE" : "/api/add-package",
  "UPDATE_PACKAGE" : "/api/update-package",
  "DELETE_PACKAGE" : "/api/delete-package",
  "PLUGIN_DATA_PACKAGE" : "/api/get-name-package",

  "LIST_SALELOG" : "/api/list-salelog",
  "LIST_SALELOG_WITH_ID" : "/api/list-salelog?id=",
  "ADD_SALELOG" : "/api/add-salelog",
  "UPDATE_SALELOG" : "/api/update-salelog",
  "DELETE_SALELOG" : "/api/delete-salelog",

  "DATA_SALE" : "/api/get-data-sale",
  "LIST_SALE" : "/api/list-sale",
  "LIST_SALE_WITH_ID" : "/api/list-sale?id=",
  "ADD_SALE" : "/api/add-sale",
  "UPDATE_SALE" : "/api/update-sale",
  "DELETE_SALE" : "/api/delete-sale",

  "LIST_KEYORDER" : "/api/list-keyorder",
  "LIST_KEYORDER_WITH_ID" : "/api/list-keyorder?id=",
  "ADD_KEYORDER" : "/api/add-keyorder",
  "UPDATE_KEYORDER" : "/api/update-keyorder",
  "DELETE_KEYORDER" : "/api/delete-keyorder",

  "LIST_KEY" : "/api/list-key",
  "LIST_KEY_WITH_ID" : "/api/list-key?id=",
  "ADD_KEY" : "/api/add-key",
  "UPDATE_KEY" : "/api/update-key",
  "DELETE_KEY" : "/api/delete-key",

  "PLUGIN_LIST_COMPANY" : "/api/plugin-list-company",
  "PLUGIN_LIST_COMPANY_BY_ID" : "/api/plugin-list-company-by-id",
  "PLUGIN_LIST_COMPANY_WITH_ID" : "/api/plugin-list-company?id=",
  "PLUGIN_ADD_COMPANY" : "/api/plugin-add-company",
  "PLUGIN_UPDATE_COMPANY" : "/api/plugin-update-company",
  "PLUGIN_DELETE_COMPANY" : "/api/plugin-delete-company",
  "PLUGIN_DATA_COMPANY" : "/api/plugin-get-data-company",

  "LIST_COMPANY" : "/api/list-company",
  "LIST_COMPANY_WITH_ID" : "/api/list-company?id=",
  "ADD_COMPANY" : "/api/add-company",
  "UPDATE_COMPANY" : "/api/update-company",
  "DELETE_COMPANY" : "/api/delete-company",
  "DATA_COMPANY" : "/api/get-data-company",

  "LIST_LINK" : "/api/list-link",
  "LIST_LINK_WITH_ID" : "/api/list-link?id=",
  "ADD_LINK" : "/api/add-link",
  "UPDATE_LINK" : "/api/update-link",
  "DELETE_LINK" : "/api/delete-link",
  "GET-LINK-BY-ID" : "/api/link-by-id",

  "LIST_FEATURE" : "/api/list-feature",
  "ADD_FEATURE" : "/api/add-feature",
  "UPDATE_FEATURE" : "/api/update-feature",
  "DELETE_FEATURE" : "/api/delete-feature",
  "DATA_CHOOSE_FEATURE" : "/api/get-feature-choose",

  "LIST_PLUGIN_ORDER" : "/api/plugin-list-order",
  "LIST_PLUGIN_ORDER_BY_ID" : "/api/plugin-list-order-by-id",
  "ADD_PLUGIN_ORDER" : "/api/plugin-add-order",
  "UPDATE_PLUGIN_ORDER" : "/api/plugin-update-order",
  "DELETE_PLUGIN_ORDER" : "/api/plugin-delete-order",
  "UPDATE_SLUG" : "/api/plugin-update-slug",

  "PLUGIN_LIST_USER" : "/api/plugin-list-user",
  "PLUGIN_ADD_USER" : "/api/plugin-add-user",
  "PLUGIN_ADD_SALE" : "/api/plugin-add-sale",
  "PLUGIN_UPDATE_USER" : "/api/plugin-update-user",
  "PLUGIN_DELETE_USER" : "/api/plugin-delete-user",
  "PLUGIN_RESET_PASSWORD" : "/api/plugin-reset-password",
  "PLUGIN_UPDATE_PASSWORD" : "/api/plugin-update-password",

  "PLUGIN_UPDATE_STATUS" : "/api/plugin-update-status",
  "PLUGIN_LOGIN_ADMIN" : "/api/plugin-login_admin",
  "PLUGIN_GET_USER_BYID" : "/api/plugin-get-user-byID",
  "PLUGIN_GET_USER_BY_BODY" : "/api/plugin-get-user-byID-with-body",

  "PLUGIN_LIST_ROLE" : "/api/plugin-list-role",
  "PLUGIN_ADD_ROLE" : "/api/plugin-add-role",
  "PLUGIN_UPDATE_ROLE" : "/api/plugin-update-role",
  "PLUGIN_DELETE_ROLE" : "/api/plugin-delete-role"
};
