export default {
  "BASE_URL" : "https://api.thulamua.com",
  //"BASE_URL" : "http://localhost:3008",
  "GHTK_URL" : "https://services.ghtklab.com",
  "LOGIN" : "/api/login",
  "LIST_USER": "/api/list_user",
  "ADD_USER":"/api/add_user",
  "UPDATE_USER":"/api/update_user",
  "DELETE_USER":"/api/delete_user",
  "UPLOAD_AVATAR": "/api/upload_avatar",

  "LIST_CATEGORY": "/api/list_category",
  "ADD_CATEGORY": "/api/add_category",
  "UPDATE_CATEGORY": "/api/update_category",
  "DELETE_CATEGORY": "/api/delete_category",
  "UPLOAD_CATEGORY": "/api/upload_category",

  "LIST_BRAND": "/api/list_brand",
  "ADD_BRAND": "/api/add_brand",
  "UPDATE_BRAND": "/api/update_brand",
  "DELETE_BRAND": "/api/delete_brand",
  "UPLOAD_BRAND": "/api/upload_brand",

  "LIST_PRODUCT": "/api/list_product",
  "LIST_PRODUCT_CATEGORY": "/api/list_product_category",
  "ADD_PRODUCT": "/api/add_product",
  "UPDATE_PRODUCT": "/api/update_product",
  "DELETE_PRODUCT": "/api/delete_product",
  "UPLOAD_PRODUCT": "/api/upload_product",
  "UPLOAD_PRODUCT_MULTIPLE": "/api/upload_product_multiple",

  "LIST_ORDER": "/api/list_order",
  "GET_DETAIL_TRANSPORT": "/api/get_detail_transport",
  "GET_LIST_TRANSPORT": "/api/get_list_transport",
  "LIST_ORDER_DETAIL": "/api/list_order_detail",
  "LIST_ORDER_BY_USER": "/api/list_order_by_user",
  "ADD_ORDER": "/api/add_order",
  "PRINT_ORDER": "/api/print_order",

  "LIST_DEAL": "/api/list_deal",
  "ADD_DEAL": "/api/add_deal",
  "UPDATE_DEAL": "/api/update_deal",
  "DELETE_DEAL": "/api/delete_deal",
  "UPLOAD_DEAL": "/api/upload_deal",

  "LIST_COUNT_ORDER": "/api/list_count_order",

  "LIST_BANNER": "/api/get_banner",
  "GET_BANNER_BY_ID": "/api/get_banner_by_id",
  "ADD_BANNER": "/api/add_banners",
  "UPADTE_BANNER": "/api/update_banner",
  "DELETE_BANNER": "/api/delete_banner",
  "UPLOAD_BANNER": "/api/upload_banner",

  "LIST_SEO_INFO": "/api/get_seo_info",
  "GET_SEO_INFO_BY_PRODUCT": "/api/get_seo_info_by_product",
  "ADD_SEO_INFO": "/api/add_seo_info",
  "UPDATE_SEO_INFO": "/api/update_seo_info",
  "DELETE_SEO_INFOR": "/api/delete_seo_info",
  "UPLOAD_SEO_INFO": "/api/upload_seo_info",

  "LIST_MULTI_IMAGE": "/api/get_multi_image",
  "LIST_IMAGE_BY_PRODUCT": "/api/get_multi_image_by_product",
  "ADD_MULTI_IMAGE": "/api/add_multi_image",
  "UPDATE_MULTI_IMAGE": "/api/update_multi_image",
  "UPLOAD_MULTI_IMAGE": "/api/upload_multi_image",

  "LIST_SUGGEST_ITEM": "/itemSdk",
  "LIST_SUGGEST_ITEM_COMPANY": "/itemSdk/",
  "LIST_SUGGEST_ITEM_ADMIN": "/itemSdk/admin/",
  "SEARCH_SUGGEST_ITEM_ADMIN": "/itemSdk/admin/search/",
  "SEARCH_SUGGEST_ITEM_COMPANY": "/itemSdk/search/",
  "ADD_SUGGEST_ITEM": "/itemSdk",
  "UPDATE_SUGGEST_ITEM": "/itemSdk/",
  "UPLOAD_IMAGE": "/itemSdk/upload_image",
  "UPLOAD_IMAGE_MAKEUP": "/itemSdk/upload_image_makeup",
  "UPLOAD_IMAGE_BRAND": "/itemSdk/upload_image_brand",
  "DELETE_SUGGEST_ITEM": "/itemSdk/deleteItem",
  "LIST_SDK": "/sdk",

  "LIST_BRAND": "/brands",
  "LIST_BRAND_COMPANY": "/brands/",
  "ADD_BRAND": "/add-brand",
  "UPDATE_BRAND": "/update-brand",
  "DELETE_BRAND": "/delete-brand",

  "LIST_BRAND_PLUGIN": "/brand-plugin",
  "LIST_BRAND_PLUGIN_COMPANY": "/brand-plugin/",
  "ADD_BRAND_PLUGIN": "/add-brand-plugin",
  "UPDATE_BRAND_PLUGIN": "/update-brand-plugin",
  "DELETE_BRAND_PLUGIN": "/delete-brand-plugin",

  "LIST_PRODUCT": "/product",
  "LIST_PRODUCT_HAIR": "/product_hair",
  "LIST_PRODUCT_COMPANY": "/product/",
  "LIST_PRODUCT_COMPANY_HAIR": "/product_hair/",
  "ADD_PRODUCT": "/add-product",
  "ADD_PRODUCT_HAIR": "/add-product-hair",
  "UPDATE_PRODUCT": "/update-product",
  "DELETE_PRODUCT": "/delete-product",

  "LIST_TYPE": "/types",
  "LIST_TYPE_COMPANY": "/types/",
  "ADD_TYPE": "/add-type",
  "UPDATE_TYPE": "/update-type",
  "DELETE_TYPE": "/delete-type",

  "LIST_COLOR": "/colors",
  "LIST_COLOR_COMPANY": "/colors/",
  "LIST_COLOR_SELECT": "/color-select",
  "ADD_COLOR": "/add-color",
  "UPDATE_COLOR": "/update-color",
  "DELETE_COLOR": "/delete-color",

  "LIST_HISTORY_SKIN": "/api/get-history-skin",
  "LIST_HISTORY_SKIN_BY_CONDITION": "/api/get-history-skin-by-condition",
  "ADD_HISTORY_SKIN": "/api/add-history-skin",


  "LIST_TYPE_PRODUCT": "/api/list-type-product",
  "ADD_TYPE_PRODUCT": "/api/add-type-product",
  "UPDATE_TYPE_PRODUCT": "/api/update-type-product",
  "DELETE_TYPE_PRODUCT": "/api/delete-type-product",


  "LIST_TYPE_SDK": "/api/list-type-sdk",
  "ADD_TYPE_SDK": "/api/add-type-sdk",
  "UPDATE_TYPE_SDK": "/api/update-type-sdk",
  "DELETE_TYPE_SDK": "/api/delete-type-sdk"
};
